apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CgkJCSJhdXRoIjogIlZWTkZVazVCVFVVNloyaDFYekZXUkhkd2J6TkJWbWc1TWtWNGFHWlpaVk5XVTFOWU1sbEZaVGhWV1RCMWFVUTVOdz09IgoJCX0sCgkJImdoY3IuaW8iOiB7CgkJCSJhdXRoIjogImJYVnlZV1JuWVdScWFXRm9iV1ZrYjNZNloyaHdYMmxXWld0M2EyTkZWR3hEUjNoMFpuQnZjM1pFZVZNNFJqWkljbmhWZERFeFlYVTRaQT09IgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiWTI5a1pYTndZV05sYzJSbGRqcGtaakJsWlRaaFpDMW1PV0l5TFRReU0yTXRPRGM0WmkwMk16VmtNR001TkdSall6ST0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiWC1NZXRhLVNvdXJjZS1DbGllbnQiOiAiZ2l0aHViL2NvZGVzcGFjZXMiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
