{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: proxy-service
          image: "{{ .Values.proxyService.image.repository }}:{{ .Values.proxyService.image.tag }}"
          imagePullPolicy: {{ .Values.proxyService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.proxyService.service.targetPort }}
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
          resources: {{- toYaml .Values.proxyService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.proxyService.service.type }}
  selector:
    app: proxy-service
  ports:
    - port: {{ .Values.proxyService.service.port }}
      targetPort: {{ .Values.proxyService.service.targetPort }}
{{- end }}
